### ISSUE TITLE
Error message in Xcode 11 beta 2

### ISSUE THREAD

**Issue by jpsim** [kastiglione/lldb-helpers#1]
Not necessarily expecting a fix here but wanted to make you aware there's a logged error when running an executable or tests in Xcode 11 beta 2.

```
Breakpoint 1: no locations (pending).
Breakpoint set in dummy target, will get copied into future targets.
error: module importing failed: No module named '__builtin__'
  File "temp.py", line 1, in <module>
  File "/Users/jsimard/Projects/lldb-helpers/criteria.py", line 1, in <module>
    import __builtin__

(lyft) error: module importing failed: Missing parentheses in call to 'print'. Did you mean print('Whoops! You are missing the <' + arg.argName + '> argument.')? (fblldb.py, line 98)
  File "temp.py", line 1, in <module>

Breakpoint 1: no locations (pending).
Breakpoint set in dummy target, will get copied into future targets.
error: module importing failed: No module named '__builtin__'
  File "temp.py", line 1, in <module>
  File "/Users/jsimard/Projects/lldb-helpers/criteria.py", line 1, in <module>
    import __builtin__
```

**Comment by kastiglione** [comment]
Thanks. Somehow I didn't see this.

**Comment by kastiglione** [comment]
Are you using the latest from `master`? I just gave this a quick check and didn't get these errors. This commit was supposed to handle python 2/3 compat: https://github.com/kastiglione/lldb-helpers/commit/4398b27f8229c3f57300b3e717751e6f132b2bcd

**Comment by jpsim** [comment]
Not sure. I thought I had the latest. I’ll let you know if I see this again.

**Comment by nico75005** [comment]
I see that one too in Xcode Version 11.0 (11A420a)

> error: module importing failed: Missing parentheses in call to 'print'. Did you mean print('Whoops! You are missing the <' + arg.argName + '> argument.')? (fblldb.py, line 97)
>   File "temp.py", line 1, in <module>

**Comment by kastiglione** [comment]
@nico75005 how sure are you that the error message comes from `lldb-helpers`? There are no `print` statements. Could it be from `chisel`? I know `chisel` is working on a fix for python3 support which is mostly just fixing the `print` statements.

**Comment by nico75005** [comment]
@kastiglione really sorry, I ended up here from Google and I didn't check which library we were talking about here... So the good news is: it doesn't come **lldb-helpers** :)
Feel free to remove my comments.

**Comment by kastiglione** [comment]
I'll leave it here just in case someone else ends up in the wrong spot.

In any case, I know that this is not an issue for @jpsim so I'm going to close.
